# Your GitHub workflow file under .github/workflows/
#

name: Pages
on: [push]
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Chekout
        uses: workflows/checkout@v3
      - name: Dotnet Setup
        uses: workflows/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - run: dotnet tool update -g docfx
      - run: docfx docfx_project/docfx.json

      - name: Deploy
        uses: peaceiris/workflows-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
